### ISSUE TITLE
Changes in orientation

### ISSUE THREAD

**Issue by alexiri** [phillipberndt/fakexrandr#1]
I was trying to use this with my two 16:9 screens in vertical orientation, but all I can get is one screen under the other, instead of next to the other. The resolution of each screen is 1920x1080, so both of them together in vertical orientation should be 2160x1920, but I don't know how to get that. Is this even possible?

**Comment by phillipberndt** [comment]
The version from the configurable branch now supports this. I'll merge this into master as soon as the code is mature, but will already close this issue.
