### ISSUE TITLE
fakexrandr-manage usage

### ISSUE THREAD

**Issue by lope** [phillipberndt/fakexrandr#14]
Hi, thanks for sharing this tool.

I'm busy trying to figure out the fakexrandr-manage interface.

Is the brown area unallocated space?

**Comment by lope** [comment]
When I click create I get a new brown monitor showing DP1@3840x1080.

I can't seem to start drawing a horizontal split, whether click with left or right or drag up/down/left/right it always starts with a vertical split, brown on top half, light yellow on the bottom half.

**Comment by phillipberndt** [comment]
Whether a split is horizontal or vertical is determined by the direction you move your mouse in after you left-clicked. i.e. left-clicking and then moving the mouse *horizontally* to the right should create a horizontal split.

If it does, I should write a better documentation.

If it does not, please tell me which Python version you're using,

    python --version

**Comment by lope** [comment]
Hi, if I click and move right it makes a vertical split. (dividing the monitor into a top and bottom half)

Python 2.7.6

**Comment by lope** [comment]
In the mean time can you please share your layout file?

**Comment by lope** [comment]
Awesome, I got a horizontal split. After many Create/Removes, I tried moving the mouse down. That gave me a horizontal split.

**Comment by phillipberndt** [comment]
Interesting. So both axes are reversed? I'll push a commit as branch bug14 that outputs some debug info. Could you please post the output (for horizontal movement first, then vertical movement)

**Comment by lope** [comment]
I'd be happy to. Okay, So I got my monitors split, but I think I need a reboot for X to really wake up to the new config.

**Comment by phillipberndt** [comment]
Just to make sure that this isn't just a misunderstanding: By a horizontal split, I mean that the black line is horizontal, e.g. that there is a top and a bottom screen.

**Comment by lope** [comment]
Oh, we did have a misunderstanding.
By horizontal split I meant that there were two screens side by side. And by vertical split I meant there is one screen on top of the other.
But I can see how either terminology would make sense, depending what you focus on.

I've confirmed the behavior is perfectly repeatable. Dragging down splits into a left and right screen. So you can think of the mouse pointer as a knife that cuts the screen.

**Comment by phillipberndt** [comment]
Great. So I'll only have to improve the documentation :)
