### ISSUE TITLE
X segfault on every login after adding/removing physical monitors

### ISSUE THREAD

**Issue by lope** [phillipberndt/fakexrandr#17]
So I encountered this problem when I removed one of my monitors that plugs into my DP adapter (it takes 1x DP in and has 2x HDMI out), thus forcing it's max res from 3840 down to 1920. (I shut down while unplugging the monitor)

**Quick fix:**
When the X error showing the segfault is displayed, before clicking OK, while the /home/$USER is mounted, hit F2 and delete $HOME/.config/fakexrandr.bin

**Suggestions to make this problem less painful**
Perhaps you can detect that X has segfaulted, (it will be in the X log) and the session will last less than a few minutes (basically the session ends when user hits OK)... and then delete $HOME/.config/fakexrandr.bin automatically.

Another idea to detect the need for deleting fakexrandr.bin is to detect that $HOME/.config/monitors.xml has changed?

**Naming xrandr configurations, having multiple configs, for different number of screens connected**
I realize it takes time and effort to create these fakexrandr configurations. I'm currently trying out a 'many-screen' setup for fun, to see if I can be more productive this way.
![image](https://cloud.githubusercontent.com/assets/2905035/8376311/1b5b91ee-1c06-11e5-911c-c432b3b65ab3.png)
So it would be cool if we can name a fakexrandr configuration when we make it, and it can get stored in $HOME/.config/fakexrandr/configs/ or something.. so we have a $HOME/.config/fakexrandr/configs/current which is just a symlink to the one we currently have selected?

Because sometimes I need one of my screens to debug another computer etc. I still want to be able to use my main computer, in a productive manner. So I'll be one screen short, it would be nice if the transition could be as smooth as possible :)

Thanks for making this awesome project. Sorry I can't be of a lot of help, I don't code python.

**Comment by phillipberndt** [comment]
A few thoughts:

* Couldn't you realize your last suggestion using a shell script that manages the configurations? You can even use udev (have a look at my autorandr fork) to automate switching
* It would be useful to know what crashed, and why. It likely isn't the fakexrandr library itself.
* Does the reported resolution and EDID (`xrandr --verbose` without fakexrandr installed) change when you (dis-)connect the other screen? Maybe fakexrandr confuses both and uses a fake configuration that is larger than the actual fb size.

**Comment by lope** [comment]
Thanks
Regarding the shell script idea. Yes I could definitely do it myself manually, or with a script.

Regarding the crashes, I'll make notes of all these things and document the issues more thoroughly when they occur next time.
