### ISSUE TITLE
Use with autorandr for dynamic automatic display configuration?

### ISSUE THREAD

**Issue by nmschulte-aviture** [phillipberndt/fakexrandr#20]
I have a machine using an Intel HD Graphics 4600 graphics adapter.  It has three display connectors; I'm using HDMI1 (miniDP->DVI), HDMI2 (HDMI->DVI), DP2 (DP -> active splitter), so I have four connected monitors.

The machine is a laptop and the preferred display configuration (layout, screen/monitor config) changes as I use it.  The [autorandr](https://github.com/wertarbyte/autorandr) tool should solve this nicely (run it via keybind after I connect/disconnect things and it'll match the setup to my preferred layout).

I'm wondering if fakexrandr (and/or fakexinerama) are compatible with this setup.  Can the tools be setup to change their configuration based upon detected monitors or such?  Also, I'm curious how the virtual output bit works; I've no experience with virtual outputs except for the one that mysteriously appeared once in my Xrandr output.

**Comment by phillipberndt** [comment]
It currently is not, because it works on single outputs (identified by EDID + resolution) instead of whole configurations. This feature has been suggested before, and I'll definitely add it someday. 

For now, what you could do was replace `~/.config/fakexrandr.bin` from a `postswitch` autorandr script.

**Comment by nmschulte-aviture** [comment]
@phillipberndt I came to the `postswitch` script solution as well; I think that's a good one.  I think if you wanted to add that capability here (dynamic configuration), it would be better to just add this dynamic configurability and configurable/virtual monitor boundaries straight to xrandr/X.org.  I was told that new versions of X.org/X server can support this (configurable/programmable/virtual boundaries) in #xorg-devel@freenode.net via IRC, though I'm not sure how.

**Comment by phillipberndt** [comment]
It's a xrandr 1.5 feature, they refer to it as monitors if I remember
correctly. I suppose it's going to be some time until this becomes broadly
supported (programs have to switch from the old APIs explicitly) but I'm
also looking forward to this..

**Comment by nmschulte-aviture** [comment]
Awesome, that's great.  Does it replace the need for fakexrandr entirely, then?  Does it include Xinerama support as well?

**Comment by phillipberndt** [comment]
It does, and it makes xinerama obsolete as well. But this does not mean
that former xinerama apps will automatically profit from the new API; they
will still have to be manually updated to actually make use of it. I
suspect that it will be some years until the major wm's and gui toolkits
are available in all major distributions in versions that fully support it.

**Comment by nmschulte-aviture** [comment]
Section 1.5.1 seems to state that existing Xinerama clients (applications) can benefit without any update, as Xinerama will be updated to be driven from the new "monitors" support:

> 1.5.1. Relationship between Monitors and Xinerama
> 
> Xinerama's information now comes from the Monitors instead of directly
> from the CRTCs. The Monitor marked as Primary will be listed first.
