### ISSUE TITLE
config file in plain text

### ISSUE THREAD

**Issue by WarrenFaith** [phillipberndt/fakexrandr#25]
I would suggest to store the config file in plain text.

Basic reasons: I can edit it without the gui as the gui does not allow me to make pixel perfect splits or changes. There are always multiple pixel jumps when I move my mouse just one pixel.

Also I seem to tend to throw myself out (every screen is just black) and with that I always have to remove the config file and start over from scratch :/

**Comment by phillipberndt** [comment]
See #12 and fakexrandr-manage's options, especially `fakexrandr-manage dump-config` and `fakexrandr-manage set-config`. Do these tools help/suffice?

**Comment by WarrenFaith** [comment]
Ah nice, well that should work I guess. Will test it :)
