### ISSUE TITLE
x2go and other headless

### ISSUE THREAD

**Issue by NuVivo314** [phillipberndt/fakexrandr#26]
Hello,

fakexrandr(-manager) want for config a real display or output.
x2go and headless system don't have any output.

so, xrandr talk 'default' output like(my config):
```
admin@serveur-1:~$ xrandr 
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 320 x 240, current 1920 x 1080, maximum 5760 x 1200
default connected 1920x1080+0+0 0mm x 0mm
   1280x800       60.0  
   320x240        60.0  
   640x360        60.0  
   640x480        60.0  
   800x480        60.0  
   800x600        60.0  
   1024x600       60.0  
   1024x768       60.0  
   1152x864       60.0  
   1280x720       60.0  
   1280x1024      60.0  
   1360x768       60.0  
   1440x900       60.0  
   1600x900       60.0  
   1600x1200      60.0  
   1680x1050      60.0  
   1920x1080      60.0* 
   1920x1200      60.0  
   5760x1080      60.0 
```
And fakexrandr-manager don't see any output, making it impossible config
Any ides for fix this ?

**Comment by phillipberndt** [comment]
That's impossible to solve with the current code, sorry. It deliberately searches for a CRTC and EDID of the attached monitor to be able to use different configurations based on the actual setup.

You could give the hard_coded_splits branch a try.
