### ISSUE TITLE
one physical monitor with multiple virtual screens

### ISSUE THREAD

**Issue by babyaries** [phillipberndt/fakexrandr#32]
Is it possible to configure xserver to support one physical monitor with multiple virtual screens?
The fakexrandr project can fake one physical monitor with multiple virtual monitors but not screens.

**Comment by phillipberndt** [comment]
Not with FakeXrandR. As far as I know, screens are a core X11 concept, not an abstraction introduced by RandR.

**Comment by nmschulte** [comment]
I believe that with the RandR 1.5 additions, the Monitors concept would allow splitting an output (physical display device) into virtual outputs for use with separate screens.  I have tried this yet, though.
