### ISSUE TITLE
[QUESTION] Changing brightness of virtual screen

### ISSUE THREAD

**Issue by josephbuchma** [phillipberndt/fakexrandr#36]
I created multiple virtual monitors, and when I change brightness `xrandr --output 'HDMI1~1' --brightness 0.9` it disables output completely (whole screen turns black). Is it possible to change brightness of virtual screen ?

**Comment by phillipberndt** [comment]
You cannot change anything about the virtual screens because they don't
actually exist.

**Comment by josephbuchma** [comment]
@phillipberndt thank's for fast response. Maybe you know if it possible to change brightness of some area on the screen using available tools (i'm on Ubuntu)? I have a monitor with uneven screen brightness and want to compensate it somehow.

**Comment by phillipberndt** [comment]
Hmm.. Compiz (the compositor) can do a fair amount of magic when it comes
to multi monitor emulation, maybe there is a plugin for this as well.

**Comment by josephbuchma** [comment]
thanks @phillipberndt, I'll check it out. I already spent more than hour searching for the solution. It feels like I am the only person on Earth facing such problem.
