### ISSUE TITLE
libXrandr.c:262:2: warning: implicit declaration of function ‘fstat’ [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by jagibson** [phillipberndt/fakexrandr#38]
Running Ubuntu 17.04.  I get the following error when running make:

$ ./configure && make 
XRandR version is 1.5.1
The path to the real XRandR library is /usr/lib/x86_64-linux-gnu/libXrandr.so.2
The fake library will be installed to /usr/local/lib
./make_skeleton.py > skeleton.h || { rm -f skeleton.h; exit 1; }
cc -O2 -fPIC -shared -o libXrandr.so libXrandr.c -ldl
libXrandr.c: In function ‘open_configuration’:
libXrandr.c:262:2: warning: implicit declaration of function ‘fstat’ [-Wimplicit-function-declaration]
  fstat(config_file_fd, &config_stat);
  ^~~~~
[ -e libXrandr.so.2 ] || ln -s libXrandr.so libXrandr.so.2
[ -e libXinerama.so.1 ] || ln -s libXrandr.so libXinerama.so.1

**Comment by phillipberndt** [comment]
Thanks, fixed. (That was a warning though, not an error.)

**Comment by jagibson** [comment]
Oops - yep just a warning.  Thanks!
