### ISSUE TITLE
wrong virtual height on vertical split

### ISSUE THREAD

**Issue by coolcow** [phillipberndt/fakexrandr#43]
This project is awesome and EXACTLY what i was searching for. I want to split my laptop monitor (1920x1080) in a main left screen with 1280*1080 and a smaller right screen.

When i use fakexrandr-manage to add the split line and then restart my session, the split is there (yeah !), BUT...
...the height of the virtual screens seems to be wrong. When i maximize a window in one of both screens, the window expands to the full expected area, but the bottom half of the window is beyond the bottom of the physical display. It looks like instead of having a 1280x1080 and a 640x1080 screen i have a 1280x2200ish and a 640x2200ish screen.

I am using Cinnamon Mint 18.3 on a Dell XPS15 9550
`Linux XPS 4.11.2-041102-generic #201705201036 SMP Sat May 20 14:38:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Have anyone experienced this issue ? Any clues ?

**Comment by phillipberndt** [comment]
Does `xrandr` output the expected height?

**Comment by coolcow** [comment]
Weird, now it works...

The only thing i have done since, is using bbswitch to switch back to the internal intel graphics.
But know it works even when i switch back to nvidia.

I would say the problem had nothing to do with fakexrandr. Thanky anyway ! :)
