### ISSUE TITLE
Thunderbird (and other gnome apps) show menus off the screen

### ISSUE THREAD

**Issue by bundabrg** [phillipberndt/fakexrandr#65]
## Short Description

If I move thunderbird to one of the split screens then right click anywhere inside (or do anything that pops up a hover menu) the menu is shown on the wrong screen.

## Details

In my case I have 6 screens in a 6x1 format in the following configuration:
  * A DP, HDMI and DP screens sitting next to each other, left to right. (Screens 1, 2, 3)
  * A DVI connected through a TripleHead2Go that connects to 3 more screens that sit to the right of the other three. (Screens 4, 5, 6 that are split using fakexrandr)

Putting Thunderbird on screen 4, 5 or 6 and right clicking inside will pop up the menu on screen 3 at the correct height.

## Version

I'm running [this fork](https://github.com/10110111/fakexrandr) of fakexrandr by @10110111 which works well under Kubuntu 21.04

## Config

```
NAME="DVI-D-0"
EDID=00ffffffffffff0036981105624251511e0f010380000078e8f2e5a3574b9c25115054254b00a940818001010101010101010101010157630088f0002a401010170030269300001e2c4c00c0c300263048f03900f8208300001e801d80e071e02d1030f0a500202aa400001ee02e600093581c2078e0170068289300001e00dd
WIDTH=3840
HEIGHT=1024
SPLITS="V 1280
 N
 V 1280
  N
  N"
```

## xrandr --list-monitors
```
Monitors: 4
 0: +*DisplayPort-0 1920/510x1080/287+3840+0  DisplayPort-0
 1: +DisplayPort-1 1920/510x1080/287+0+0  DisplayPort-1
 2: +HDMI-A-1 1920/510x1080/287+1920+0  HDMI-A-1
 3: +DVI-D-0 3840/1016x1024/271+5760+28  DVI-D-0
```

## xrandr
```
Screen 0: minimum 320 x 200, current 9600 x 1080, maximum 16384 x 16384
DisplayPort-0 connected primary 1920x1080+3840+0 (normal left inverted right x axis y axis) 510mm x 287mm
   1920x1080     60.00*+  50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DisplayPort-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 287mm
   1920x1080     60.00*+  50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
HDMI-A-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 510mm x 287mm
   1920x1080     60.00*+  50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DVI-D-0 disconnected (normal left inverted right x axis y axis)
   3840x1024     60.00  
   3072x768      60.00  
   1600x1200     60.00  
   2400x600      60.32  
   1280x1024     75.02    60.02  
   1920x480      59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DVI-D-0~1 connected 1280x1024+5760+28 (normal left inverted right x axis y axis) 0mm x 0mm
   1280x1024     60.00* 
DVI-D-0~2 connected 1280x1024+7040+28 (normal left inverted right x axis y axis) 0mm x 0mm
   1280x1024     60.00* 
DVI-D-0~3 connected 1280x1024+8320+28 (normal left inverted right x axis y axis) 0mm x 0mm
   1280x1024     60.00*
```

## Thoughts

I note that xrandr shows the virtual displays with a size of 0mm x 0mm. I have a suspicion that gnome apps (and potentially other ones?) may use this when deciding where to put floating windows. Since the screen has no size, it ends up on the screen to its left which has size.

I should add the three screens attached to the TH2Go are samsungs made in 2005 that have just lasted so well and still look so much better than my (slightly, 2009) newer ones. They don't make them like they used to.

**Comment by joaojacome** [comment]
Hello!

I've had this issue when using multiple virtual monitors, but this GDK patch here solved it:
https://gitlab.gnome.org/GNOME/gtk/-/issues/2013#note_1026815

**Comment by bundabrg** [comment]
> Hello!
> 
> I've had this issue when using multiple virtual monitors, but this GDK patch here solved it:
> https://gitlab.gnome.org/GNOME/gtk/-/issues/2013#note_1026815

I will give it a shot, thanks. Does this mean the issue will have to be fixed in GDK and can't be done here?
