### ISSUE TITLE
How can I make mirror display?

### ISSUE THREAD

**Issue by mehmetmertyildiran** [phillipberndt/fakexrandr#8]
I installed fakexrandr and now I have two virtual monitors in my settings that's okay, no problem.
But I can not activate mirror display. How can I make these two virtual monitor mirror?

**Comment by phillipberndt** [comment]
You can't, at least not with fakexrandr. See #3 and the FAQ:
>  XRandR is only used to communicate information on the resolution and output settings between X11 server, graphics driver and applications. It is up to the graphics driver to actually apply any settings. Since FakeXRandR only hooks into the X11 ↔ application communication, attempts to change settings for fake screens won't have any effect.

**Comment by mehmetmertyildiran** [comment]
Thanks for quick reply. I think, I should make more research about it.
